-- DBW PLANNER V6 - MIGRAZIONE SICURA
-- Non elimina né modifica i dati di MANEGGIO VP.
-- Mantiene gli eventi DBW già presenti e li collega alla stagione 2026/27.

create table if not exists public.dbw_seasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_date date not null,
  end_date date not null,
  is_archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.dbw_teams (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.dbw_seasons(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(season_id, name)
);

create table if not exists public.dbw_training_patterns (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.dbw_teams(id) on delete cascade,
  weekday integer not null check (weekday between 1 and 7),
  start_time time not null,
  end_time time not null,
  location text not null,
  created_at timestamptz not null default now()
);

alter table public.dbw_events add column if not exists season_id bigint references public.dbw_seasons(id) on delete cascade;
alter table public.dbw_events add column if not exists team_id bigint references public.dbw_teams(id) on delete cascade;

insert into public.dbw_seasons(name,start_date,end_date)
values ('2026/27','2026-08-01','2027-06-30')
on conflict (name) do nothing;

insert into public.dbw_teams(season_id,name,sort_order)
select s.id, x.name, x.ord
from public.dbw_seasons s
cross join (values ('UNDER 12',1),('UNDER 17',2),('PRIMA SQUADRA',3)) as x(name,ord)
where s.name='2026/27'
on conflict (season_id,name) do nothing;

update public.dbw_events e
set season_id=s.id,
    team_id=t.id
from public.dbw_seasons s, public.dbw_teams t
where s.name='2026/27'
  and t.season_id=s.id
  and t.name=e.category
  and (e.season_id is null or e.team_id is null);

alter table public.dbw_seasons enable row level security;
alter table public.dbw_teams enable row level security;
alter table public.dbw_training_patterns enable row level security;

-- Policy temporanee coerenti con la V5: accesso dalla web app pubblica.
do $$ begin
  create policy "DBW seasons all" on public.dbw_seasons for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "DBW teams all" on public.dbw_teams for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "DBW patterns all" on public.dbw_training_patterns for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;

create index if not exists dbw_events_season_idx on public.dbw_events(season_id);
create index if not exists dbw_events_team_idx on public.dbw_events(team_id);
create index if not exists dbw_teams_season_idx on public.dbw_teams(season_id);
create index if not exists dbw_patterns_team_idx on public.dbw_training_patterns(team_id);
