-- ============================================================
-- DBW PLANNER V7 - ROSA, PRESENZE, MINUTI E REPORT
-- NON cancella né modifica le tabelle di MANEGGIO VP.
-- Aggiunge solo strutture DBW e una colonna a dbw_teams.
-- ============================================================

alter table public.dbw_teams
add column if not exists track_match_minutes boolean not null default true;

-- UNDER 12: nelle partite basta presenza/assenza, senza minuti.
update public.dbw_teams
set track_match_minutes = false
where upper(name) like '%UNDER 12%';

-- Tutte le altre squadre mantengono i minuti partita attivi di default.

create table if not exists public.dbw_players (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.dbw_seasons(id) on delete cascade,
  team_id bigint not null references public.dbw_teams(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dbw_players_team_idx
on public.dbw_players(team_id, active, sort_order);

alter table public.dbw_players enable row level security;

create table if not exists public.dbw_attendance (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.dbw_seasons(id) on delete cascade,
  team_id bigint not null references public.dbw_teams(id) on delete cascade,
  event_id bigint not null references public.dbw_events(id) on delete cascade,
  player_id bigint not null references public.dbw_players(id) on delete cascade,
  status text not null check (status in ('present','abs_excused','abs_unexcused')),
  minutes_played integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id, player_id)
);

create index if not exists dbw_attendance_team_idx
on public.dbw_attendance(team_id, player_id);

create index if not exists dbw_attendance_event_idx
on public.dbw_attendance(event_id);

alter table public.dbw_attendance enable row level security;

-- RLS: coerente con le policy DBW già usate dalla web app.
drop policy if exists "DBW players select" on public.dbw_players;
drop policy if exists "DBW players insert" on public.dbw_players;
drop policy if exists "DBW players update" on public.dbw_players;
drop policy if exists "DBW players delete" on public.dbw_players;

create policy "DBW players select" on public.dbw_players for select to public using (true);
create policy "DBW players insert" on public.dbw_players for insert to public with check (true);
create policy "DBW players update" on public.dbw_players for update to public using (true) with check (true);
create policy "DBW players delete" on public.dbw_players for delete to public using (true);

drop policy if exists "DBW attendance select" on public.dbw_attendance;
drop policy if exists "DBW attendance insert" on public.dbw_attendance;
drop policy if exists "DBW attendance update" on public.dbw_attendance;
drop policy if exists "DBW attendance delete" on public.dbw_attendance;

create policy "DBW attendance select" on public.dbw_attendance for select to public using (true);
create policy "DBW attendance insert" on public.dbw_attendance for insert to public with check (true);
create policy "DBW attendance update" on public.dbw_attendance for update to public using (true) with check (true);
create policy "DBW attendance delete" on public.dbw_attendance for delete to public using (true);

grant select, insert, update, delete on public.dbw_players to anon, authenticated;
grant select, insert, update, delete on public.dbw_attendance to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ============================================================
-- FINE MIGRAZIONE V7
-- ============================================================
